### PR TITLE
Use 'suggest' as a source of dependencies. getDependencies refactoring

### PR DESCRIPTION
**Pull request by hws47a**
- Use 'suggest' as a source of dependencies. 
- `getDependencies` refactoring

### CODE REVIEW

**Comment by jissereitsma** [comment]
Nice addition and great refactoring. Thanks!

**Comment by hws47a** [comment]
@jissereitsma thank you

**Comment by hws47a** [comment]
@jissereitsma  Could you please release this change?

**Comment by jissereitsma** [comment]
Done. Version 1.1.2 has been released.

**Pull request merged**
